/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalMultiplayerRouteImport } from './routes/local-multiplayer'
import { Route as OnlineMultiplayerRouteImport } from './routes/online-multiplayer'
import { Route as SinglePlayerRouteImport } from './routes/single-player'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalMultiplayerRoute = LocalMultiplayerRouteImport.update({
  id: '/local-multiplayer',
  path: '/local-multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineMultiplayerRoute = OnlineMultiplayerRouteImport.update({
  id: '/online-multiplayer',
  path: '/online-multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglePlayerRoute = SinglePlayerRouteImport.update({
  id: '/single-player',
  path: '/single-player',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local-multiplayer': typeof LocalMultiplayerRoute
  '/online-multiplayer': typeof OnlineMultiplayerRoute
  '/single-player': typeof SinglePlayerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/local-multiplayer': typeof LocalMultiplayerRoute
  '/online-multiplayer': typeof OnlineMultiplayerRoute
  '/single-player': typeof SinglePlayerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/local-multiplayer': typeof LocalMultiplayerRoute
  '/online-multiplayer': typeof OnlineMultiplayerRoute
  '/single-player': typeof SinglePlayerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/local-multiplayer' | '/online-multiplayer' | '/single-player'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/local-multiplayer' | '/online-multiplayer' | '/single-player'
  id:
    | '__root__'
    | '/'
    | '/local-multiplayer'
    | '/online-multiplayer'
    | '/single-player'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalMultiplayerRoute: typeof LocalMultiplayerRoute
  OnlineMultiplayerRoute: typeof OnlineMultiplayerRoute
  SinglePlayerRoute: typeof SinglePlayerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-multiplayer': {
      id: '/local-multiplayer'
      path: '/local-multiplayer'
      fullPath: '/local-multiplayer'
      preLoaderRoute: typeof LocalMultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-multiplayer': {
      id: '/online-multiplayer'
      path: '/online-multiplayer'
      fullPath: '/online-multiplayer'
      preLoaderRoute: typeof OnlineMultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-player': {
      id: '/single-player'
      path: '/single-player'
      fullPath: '/single-player'
      preLoaderRoute: typeof SinglePlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalMultiplayerRoute: LocalMultiplayerRoute,
  OnlineMultiplayerRoute: OnlineMultiplayerRoute,
  SinglePlayerRoute: SinglePlayerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
